import typography from "./typography.mjs";
import typographyPlugin from "@tailwindcss/typography";
import { Combinators, ExtendTheme } from "./Plugins/index.mjs";
import { merge } from "ts-deepmerge";

export default function config({ theme } = {}) {
    // Merge default settings with custom settings
    theme = merge({ extend: { ...ExtendTheme, typography } }, theme || {});

    /** @type {import('tailwindcss').Config} */
    return {
        darkMode: "class",
        theme,
        plugins: [typographyPlugin, Combinators],
        corePlugins: {
            accessibility: false,
            alignContent: false,
            alignItems: false,
            alignSelf: false,
            animation: false,
            appearance: false,
            backdropBlur: false,
            backdropBrightness: false,
            backdropContrast: false,
            backdropFilter: false,
            backdropGrayscale: false,
            backdropHueRotate: false,
            backdropInvert: false,
            backdropOpacity: false,
            backdropSaturate: false,
            backdropSepia: false,
            backgroundAttachment: false,
            backgroundBlendMode: false,
            backgroundClip: false,
            backgroundImage: false,
            backgroundOpacity: false,
            backgroundPosition: false,
            backgroundRepeat: false,
            backgroundSize: false,
            blur: false,
            borderOpacity: false,
            boxDecorationBreak: false,
            boxShadow: false,
            boxSizing: false,
            brightness: false,
            clear: false,
            container: false,
            contrast: false,
            cursor: false,
            divideColor: false,
            divideOpacity: false,
            divideStyle: false,
            divideWidth: false,
            dropShadow: false,
            fill: false,
            filter: false,
            flex: false,
            flexDirection: false,
            flexGrow: false,
            flexShrink: false,
            flexWrap: false,
            float: false,
            fontVariantNumeric: false,
            gap: false,
            gradientColorStops: false,
            grayscale: false,
            gridAutoColumns: false,
            gridAutoFlow: false,
            gridAutoRows: false,
            gridColumn: false,
            gridColumnEnd: false,
            gridColumnStart: false,
            gridRow: false,
            gridRowEnd: false,
            gridRowStart: false,
            gridTemplateColumns: false,
            gridTemplateRows: false,
            hueRotate: false,
            inset: false,
            invert: false,
            isolation: false,
            justifyContent: false,
            justifyItems: false,
            justifySelf: false,
            listStylePosition: false,
            mixBlendMode: false,
            objectFit: false,
            objectPosition: false,
            order: false,
            outline: false,
            overflow: false,
            overscrollBehavior: false,
            placeContent: false,
            placeholderColor: false,
            placeholderOpacity: false,
            placeItems: false,
            placeSelf: false,
            pointerEvents: false,
            position: false,
            resize: false,
            ringColor: false,
            ringOffsetColor: false,
            ringOffsetWidth: false,
            ringOpacity: false,
            ringWidth: false,
            rotate: false,
            saturate: false,
            scale: false,
            sepia: false,
            skew: false,
            space: false,
            stroke: false,
            strokeWidth: false,
            textOpacity: false,
            textOverflow: false,
            transform: false,
            transformOrigin: false,
            transitionDelay: false,
            transitionDuration: false,
            transitionProperty: false,
            transitionTimingFunction: false,
            translate: false,
            userSelect: false,
            visibility: false,
            zIndex: false,
        },
    };
}
