##
# Document NodeType for meta pages like imprint, etc.
#
##

'Litefyr.Integration:Document.Meta':
  abstract: true
  superTypes:
    'Litefyr.Integration:Document.ContentPage': true
    'Litefyr.Integration:Mixin.TeaserDocument.Single': true
    'Litefyr.Integration:Constraint.Document.NoSubDocument': true
    'Litefyr.Integration:Mixin.NotInMenu': true
  ui:
    label: i18n
    icon: info-circle
    position: 500
    help:
      message: i18n
