##
# Document NodeType for meta pages like imprint, etc.
#
##

'Litefyr.Integration:Document.Meta':
  abstract: true
  superTypes:
    'Litefyr.Integration:Document.ContentPage': true
    'Litefyr.Integration:Mixin.TeaserDocument.Single': true
    'Litefyr.Integration:Constraint.Document.NoSubDocument': true
    'Litefyr.Integration:Mixin.NotInMenu': true
    'Garagist.Mautic:Mixin.Email': false
    'Garagist.Mautic:Mixin.Category': false
  ui:
    label: i18n
    icon: info-circle
    group: special
    position: 500
