Neos:
  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: localhost
        port: 1025
  Flow:
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          systemLogger:
            default:
              options:
                logFileURL: '%FLOW_PATH_TEMPORARY_BASE%/Logs/System_Development.log'
                severityThreshold: '%LOG_DEBUG%'

          securityLogger:
            default:
              options:
                logFileURL: '%FLOW_PATH_TEMPORARY_BASE%/Logs/Security_Development.log'
                severityThreshold: '%LOG_DEBUG%'

          sqlLogger:
            default:
              options:
                logFileURL: '%FLOW_PATH_TEMPORARY_BASE%/Logs/Query_Development.log'
                severityThreshold: '%LOG_DEBUG%'

          i18nLogger:
            default:
              options:
                logFileURL: '%FLOW_PATH_TEMPORARY_BASE%/Logs/I18n_Development.log'
                severityThreshold: '%LOG_DEBUG%'
