Carbon:
  GeoMap:
    defaultCountry: AT
  IncludeAssets:
    Packages:
      Carbon.CodePen:
        position: 'start 10'
        Package: 'Litefyr.Integration'
        Backend:
          HeadStart:
            - https://cdn.tailwindcss.com/3.4.16(js)
            - TailwindConfig.js
