Carbon:
  GeoMap:
    defaultCountry: AT
  IncludeAssets:
    Packages:
      Carbon.CodePen:
        Package: 'Litespeed.Integration'
        Backend:
          Head:
            - https://cdn.tailwindcss.com(js)
            - TailwindConfig.js

Neos:
  Neos:
    Ui:
      frontendConfiguration:
        'Carbon.PreviewMode:Button':
          teaserView:
            nodeTypeName: 'Litespeed.Integration:Mixin.TeaserDocument'
            icon: 'fas fa-images'
            label: 'Litespeed.Integration:Backend.Main:editPreviewModes.teaserView'
