Neos:
  ContentRepository:
    labelGenerator:
      eel:
        defaultContext:
          Carbon.String: 'Carbon\Eel\EelHelper\StringHelper'
          Carbon.Array: 'Carbon\Eel\EelHelper\ArrayHelper'
  Flow:
    http:
      trustedProxies:
        proxies: '*'
    core:
      subRequestIniEntries:
        memory_limit: 2048M
    persistence:
      backendOptions:
        driver: '%env:NEOS_DB_DRIVER%'
        dbname: '%env:NEOS_DB_NAME%'
        user: '%env:NEOS_DB_USER%'
        password: '%env:NEOS_DB_PASSWORD%'
        host: '%env:NEOS_DB_HOST%'
        port: '%env:NEOS_DB_PORT%'
        charset: '%env:NEOS_DB_CHARSET%'
        defaultTableOptions:
          charset: '%env:NEOS_DB_CHARSET%'
    i18n:
      defaultLocale: '%env:DEFAULT_LOCALE%'
      fallbackRule:
        order: ['de', 'en']
    mvc:
      routes:
        'Litefyr.Integration':
          position: 'start'
        'Neos.Neos':
          variables:
            defaultUriSuffix: ''
  Neos:
    fusion:
      autoInclude:
        Litefyr.Integration: true
    Ui:
      frontendConfiguration:
        Flowpack.Media.Ui:
          showSimilarAssets: true
          queryAssetUsage: true
      resources:
        javascript:
          Litefyr.Integration:
            resource: resource://Litefyr.Integration/Public/Editors/Plugin.js
            attributes:
              type: 'module'
    userInterface:
      defaultLanguage: '%env:DEFAULT_LOCALE%'
      navigateComponent:
        nodeTree:
          loadingDepth: 1
        structureTree:
          loadingDepth: 0
      translation:
        autoInclude:
          Litefyr.Integration:
            - 'NodeTypes/*'
            - 'Backend/*'
    nodeTypes:
      groups:
        structure:
          label: 'Litefyr.Integration:Backend.Main:nodeTypes.structure'
          position: 300
        multimedia:
          label: 'Litefyr.Integration:Backend.Main:nodeTypes.multimedia'
          position: 400
        teaser:
          label: 'Litefyr.Integration:Backend.Main:nodeTypes.teaser'
          position: 500
        gallery:
          label: 'Litefyr.Integration:Backend.Main:nodeTypes.gallery'
          position: 600
        form:
          label: 'Litefyr.Integration:Backend.Main:nodeTypes.form'
          position: 1200
          collapsed: true
        special:
          label: 'Litefyr.Integration:Backend.Main:nodeTypes.special'
          position: 8000
          collapsed: true
        system:
          label: 'Litefyr.Integration:Backend.Main:nodeTypes.system'
          position: 9000
          collapsed: true
